In [6]:
import pandas as pd
changes = pd.read_csv(r'C:\Users\蒋大王\Desktop\量化\Interest_rate_investment\data\processed\treasury_yield_changes_bp.csv')
level = pd.read_csv(r'C:\Users\蒋大王\Desktop\量化\Interest_rate_investment\data\processed\treasury_yields.csv')
unrate = pd.read_csv(r'C:\Users\蒋大王\Desktop\量化\Interest_rate_investment\data\processed\macro\unemployment_snapshots.csv')
snap = [{"date": "2004-01-01", "UNRATE_20060209": "5.7"}, {"date": "2004-02-01", "UNRATE_20060209": "5.6"}, {"date": "2004-03-01", "UNRATE_20060209": "5.7"}, {"date": "2004-04-01", "UNRATE_20060209": "5.5"}, {"date": "2004-05-01", "UNRATE_20060209": "5.6"}, {"date": "2004-06-01", "UNRATE_20060209": "5.6"}, {"date": "2004-07-01", "UNRATE_20060209": "5.5"}, {"date": "2004-08-01", "UNRATE_20060209": "5.4"}, {"date": "2004-09-01", "UNRATE_20060209": "5.4"}, {"date": "2004-10-01", "UNRATE_20060209": "5.4"}, {"date": "2004-11-01", "UNRATE_20060209": "5.4"}, {"date": "2004-12-01", "UNRATE_20060209": "5.4"}, {"date": "2005-01-01", "UNRATE_20060209": "5.2"}, {"date": "2005-02-01", "UNRATE_20060209": "5.4"}, {"date": "2005-03-01", "UNRATE_20060209": "5.1"}, {"date": "2005-04-01", "UNRATE_20060209": "5.1"}, {"date": "2005-05-01", "UNRATE_20060209": "5.1"}, {"date": "2005-06-01", "UNRATE_20060209": "5.0"}, {"date": "2005-07-01", "UNRATE_20060209": "5.0"}, {"date": "2005-08-01", "UNRATE_20060209": "4.9"}, {"date": "2005-09-01", "UNRATE_20060209": "5.1"}, {"date": "2005-10-01", "UNRATE_20060209": "4.9"}, {"date": "2005-11-01", "UNRATE_20060209": "5.0"}, {"date": "2005-12-01", "UNRATE_20060209": "4.9"}, {"date": "2006-01-01", "UNRATE_20060209": "4.7"}]

In [ ]:
unrate

      snapshot_date observation_month  value
0        2006-02-09        2004-01-01    5.7
1        2006-02-09        2004-02-01    5.6
2        2006-02-09        2004-03-01    5.7
3        2006-02-09        2004-04-01    5.5
4        2006-02-09        2004-05-01    5.6
...             ...               ...    ...
36801    2026-09-04        2026-04-01    4.3
36802    2026-09-04        2026-05-01    4.3
36803    2026-09-04        2026-06-01    4.2
36804    2026-09-04        2026-07-01    4.1
36805    2026-09-04        2026-08-01    4.1

[36806 rows x 3 columns]

In [5]:
snap

[{'date': '2004-01-01', 'UNRATE_20060209': '5.7'},
 {'date': '2004-02-01', 'UNRATE_20060209': '5.6'},
 {'date': '2004-03-01', 'UNRATE_20060209': '5.7'},
 {'date': '2004-04-01', 'UNRATE_20060209': '5.5'},
 {'date': '2004-05-01', 'UNRATE_20060209': '5.6'},
 {'date': '2004-06-01', 'UNRATE_20060209': '5.6'},
 {'date': '2004-07-01', 'UNRATE_20060209': '5.5'},
 {'date': '2004-08-01', 'UNRATE_20060209': '5.4'},
 {'date': '2004-09-01', 'UNRATE_20060209': '5.4'},
 {'date': '2004-10-01', 'UNRATE_20060209': '5.4'},
 {'date': '2004-11-01', 'UNRATE_20060209': '5.4'},
 {'date': '2004-12-01', 'UNRATE_20060209': '5.4'},
 {'date': '2005-01-01', 'UNRATE_20060209': '5.2'},
 {'date': '2005-02-01', 'UNRATE_20060209': '5.4'},
 {'date': '2005-03-01', 'UNRATE_20060209': '5.1'},
 {'date': '2005-04-01', 'UNRATE_20060209': '5.1'},
 {'date': '2005-05-01', 'UNRATE_20060209': '5.1'},
 {'date': '2005-06-01', 'UNRATE_20060209': '5.0'},
 {'date': '2005-07-01', 'UNRATE_20060209': '5.0'},
 {'date': '2005-08-01', 'UNRATE_20060209': '4.9'},
 {'date': '2005-09-01', 'UNRATE_20060209': '5.1'},
 {'date': '2005-10-01', 'UNRATE_20060209': '4.9'},
 {'date': '2005-11-01', 'UNRATE_20060209': '5.0'},
 {'date': '2005-12-01', 'UNRATE_20060209': '4.9'},
 {'date': '2006-01-01', 'UNRATE_20060209': '4.7'}]

In [27]:
from pathlib import Path
import sys

ROOT = Path(r"C:\Users\蒋大王\Desktop\量化\Interest_rate_investment")

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.fred_vintages import FredVintageClient
from src.features.macro_features import snapshot_features, align_updates

In [6]:
config = yaml.safe_load(Path(r'C:\Users\蒋大王\Desktop\量化\Interest_rate_investment\config\macro.yaml').read_text(encoding='utf-8'))
config

{'base_config': 'config/base.yaml',
 'cache_dir': 'data/raw/fred_vintages',
 'output_dir': 'data/processed/macro',
 'observation_start': '2004-01-01',
 'vintage_end': None,
 'availability_lag_sessions': 1,
 'series': {'unemployment': {'id': 'UNRATE', 'kind': 'unemployment'},
  'cpi': {'id': 'CPIAUCSL', 'kind': 'price_index'},
  'core_pce': {'id': 'PCEPILFE', 'kind': 'price_index'}}}

In [17]:
config['series']

{'unemployment': {'id': 'UNRATE', 'kind': 'unemployment'},
 'cpi': {'id': 'CPIAUCSL', 'kind': 'price_index'},
 'core_pce': {'id': 'PCEPILFE', 'kind': 'price_index'}}

In [32]:
client = FredVintageClient(
    api_key=None,
    cache_dir=ROOT / config['cache_dir'],
    offline=True,
)

In [ ]:
versions = client.vintage_dates(spec['id'], start, end)

In [33]:
snapshot = client.snapshot(
    series='UNRATE',
    vintage='2006-02-09',
    observation_start='2004-01-01',
)

display(snapshot)
display(snapshot.tail(5))
print(snapshot.shape)

   snapshot_date observation_month  value
0     2006-02-09        2004-01-01    5.7
1     2006-02-09        2004-02-01    5.6
2     2006-02-09        2004-03-01    5.7
3     2006-02-09        2004-04-01    5.5
4     2006-02-09        2004-05-01    5.6
5     2006-02-09        2004-06-01    5.6
6     2006-02-09        2004-07-01    5.5
7     2006-02-09        2004-08-01    5.4
8     2006-02-09        2004-09-01    5.4
9     2006-02-09        2004-10-01    5.4
10    2006-02-09        2004-11-01    5.4
11    2006-02-09        2004-12-01    5.4
12    2006-02-09        2005-01-01    5.2
13    2006-02-09        2005-02-01    5.4
14    2006-02-09        2005-03-01    5.1
15    2006-02-09        2005-04-01    5.1
16    2006-02-09        2005-05-01    5.1
17    2006-02-09        2005-06-01    5.0
18    2006-02-09        2005-07-01    5.0
19    2006-02-09        2005-08-01    4.9
20    2006-02-09        2005-09-01    5.1
21    2006-02-09        2005-10-01    4.9
22    2006-02-09        2005-11-01    5.0
23    2006-02-09        2005-12-01    4.9
24    2006-02-09        2006-01-01    4.7

   snapshot_date observation_month  value
20    2006-02-09        2005-09-01    5.1
21    2006-02-09        2005-10-01    4.9
22    2006-02-09        2005-11-01    5.0
23    2006-02-09        2005-12-01    4.9
24    2006-02-09        2006-01-01    4.7

(25, 3)

In [38]:
snapshot, row = [], []
snapshot1 = client.snapshot(
    series='UNRATE',
    vintage='2006-02-09',
    observation_start='2004-01-01',
)
snapshot.append(snapshot1)

row1 = snapshot_features(
    snapshot=snapshot1,
    name='unemployment',
    kind='unemployment',
)

row.append(row1)
updates = pd.DataFrame(row)
updates

,snapshot_date,observation_month,unemployment_rate,unemployment_change_1m_pp
0,2006-02-09,2006-01-01,4.7,-0.2

In [39]:
from pathlib import Path
import sys
import pandas as pd

ROOT = Path(r"C:\Users\蒋大王\Desktop\量化\Interest_rate_investment")
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.fred_vintages import FredVintageClient
from src.features.macro_features import snapshot_features, align_updates

client = FredVintageClient(
    api_key=None,
    cache_dir=ROOT / "data/raw/fred_vintages",
    offline=True,
)

In [40]:
snapshot1 = client.snapshot("UNRATE", "2006-02-09", "2004-01-01")
snapshot2 = client.snapshot("UNRATE", "2006-03-10", "2004-01-01")

display(snapshot1.tail(3))
display(snapshot2.tail(3))

   snapshot_date observation_month  value
22    2006-02-09        2005-11-01    5.0
23    2006-02-09        2005-12-01    4.9
24    2006-02-09        2006-01-01    4.7

   snapshot_date observation_month  value
23    2006-03-10        2005-12-01    4.9
24    2006-03-10        2006-01-01    4.7
25    2006-03-10        2006-02-01    4.8

In [41]:
updates = pd.DataFrame([
    snapshot_features(snapshot1, "unemployment", "unemployment"),
    snapshot_features(snapshot2, "unemployment", "unemployment"),
])

display(updates)

,snapshot_date,observation_month,unemployment_rate,unemployment_change_1m_pp
0,2006-02-09,2006-01-01,4.7,-0.2
1,2006-03-10,2006-02-01,4.8,0.1

In [42]:
levels = pd.read_csv(
    ROOT / "data/processed/treasury_yields.csv",
    parse_dates=["date"],
)
dates = pd.DatetimeIndex(levels["date"]).sort_values()

features, lineage = align_updates(
    updates,
    dates,
    name="unemployment",
    lag_sessions=1,
)

display(features.join(lineage).loc["2006-03-09":"2006-03-14"])

,unemployment_rate,unemployment_change_1m_pp,unemployment_snapshot_date,unemployment_available_date,unemployment_observation_month
signal_date,,,,,
2006-03-09,4.7,-0.2,2006-02-09,2006-02-10,2006-01-01
2006-03-10,4.7,-0.2,2006-02-09,2006-02-10,2006-01-01
2006-03-13,4.8,0.1,2006-03-10,2006-03-13,2006-02-01
2006-03-14,4.8,0.1,2006-03-10,2006-03-13,2006-02-01